apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-external-secret
  namespace: securebank
spec:
  # Synchronise toutes les heures
  # Si le secret change dans Vault → K8s mis à jour automatiquement
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    # Nom du Secret Kubernetes créé automatiquement
    name: auth-secret
  data:
    # Récupère JWT_SECRET depuis Vault
    - secretKey: JWT_SECRET
      remoteRef:
        key: securebank/auth
        property: JWT_SECRET
