apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: common-external-secret
  namespace: securebank
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    # Secret partagé entre les 3 services
    name: common-secret
  data:
    # Récupère chaque champ depuis Vault
    - secretKey: ENVIRONMENT
      remoteRef:
        key: securebank/common
        property: ENVIRONMENT
    - secretKey: JWT_ALGORITHM
      remoteRef:
        key: securebank/common
        property: JWT_ALGORITHM
    - secretKey: ACCESS_TOKEN_EXPIRE_MINUTES
      remoteRef:
        key: securebank/common
        property: ACCESS_TOKEN_EXPIRE_MINUTES
