apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # Nom de l'ExternalSecret
  name: harbor-external-secret
  namespace: securebank
spec:
  # Vérifie et synchronise toutes les heures
  refreshInterval: 1h
  secretStoreRef:
    # Référence au SecretStore qu'on vient de créer
    name: vault-secret-store
    kind: SecretStore
  target:
    # Nom du Secret Kubernetes qui sera créé automatiquement
    name: harbor-secret
    # Type docker-registry = format spécial pour pull les images
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        # Format JSON requis par Kubernetes pour les registry privés
        .dockerconfigjson: |
          {"auths":{"{{ .server }}":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    # Récupère le champ username depuis Vault
    - secretKey: username
      remoteRef:
        key: securebank/harbor
        property: username
    # Récupère le champ password depuis Vault
    - secretKey: password
      remoteRef:
        key: securebank/harbor
        property: password
    # Récupère le champ server depuis Vault
    - secretKey: server
      remoteRef:
        key: securebank/harbor
        property: server
