apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: securebank
  labels:
    app: auth-service
    team: devsecops
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 192.168.157.20/securebank/auth-service:fde50480
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            # JWT_SECRET injecté depuis auth-secret créé par ESO
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            # Variables communes injectées depuis common-secret
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: ENVIRONMENT
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_ALGORITHM
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: ACCESS_TOKEN_EXPIRE_MINUTES
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        # harbor-secret créé automatiquement par ESO depuis Vault
        - name: harbor-secret
