apiVersion: v1
kind: Service
metadata:
  # Nom du service — c'est aussi son nom DNS dans le cluster
  # account-service peut appeler http://auth-service:8000
  name: auth-service
  namespace: securebank
  labels:
    app: auth-service
    team: devsecops
    environment: staging
spec:
  # ClusterIP = accessible uniquement dans le cluster
  # Les autres microservices peuvent l'appeler par son nom
  type: ClusterIP
  # Redirige le trafic vers les pods qui ont ce label
  selector:
    app: auth-service
  ports:
    - name: http
      # Port du Service — ce que les autres appellent
      port: 8000
      # Port du container — où FastAPI écoute
      targetPort: 8000
      protocol: TCP

## Le lien Deployment → Service

##Service selector: app=auth-service
        ↓
##Cherche tous les pods avec label app=auth-service
        ↓
##Deployment crée des pods avec label app=auth-service
        ↓
##Service trouve les pods et envoie le trafic ✅
