apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: securebank
  labels:
    app: auth-service
    team: devsecops
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
