apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: securebank
  labels:
    app: account-service
    team: devsecops
    environment: staging
data:
  PORT: "8001"
  ENVIRONMENT: "staging"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  TRANSACTION_SERVICE_URL: "http://transaction-service:8002"
  JWT_ALGORITHM: "HS256"
