apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: securebank
  labels:
    app: transaction-service
    team: devsecops
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: 192.168.157.20/securebank/transaction-service:latest
          ports:
            - containerPort: 8002
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            # JWT_SECRET pour valider les tokens
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            # Variables communes
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: ENVIRONMENT
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_ALGORITHM
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: harbor-secret
