apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: securebank
  labels:
    app: transaction-service
    team: devsecops
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
