apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  # Nom du SecretStore — référencé dans les ExternalSecrets  fichier de configuration de la connexion entre ESO et Vault
  name: vault-secret-store
  namespace: securebank
spec:
  provider:
    vault:
      # Adresse de notre Vault sur vm-vault
      server: "http://192.168.157.30:8200"
      # Chemin du moteur KV dans Vault
      path: "secret"
      # Version KV — on utilise v2
      version: "v2"
      auth:
        # Authentification par token statique
        # Plus tard  on utilisera Kubernetes Auth (plus sécurisé)
        tokenSecretRef:
          # Nom du Secret Kubernetes qui contient le token Vault
          # On va le créer juste après
          name: vault-token
          key: token
